### ISSUE TITLE
Wrangle an example dataset for MorPhiC

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#1]
From hca-ebi-wrangler-central created by [ESapenaVentura](https://github.com/ESapenaVentura): ebi-ait/hca-ebi-wrangler-central#1174  

Using the MVP instructions and spreadsheet:

- Find a suitable dataset
- Wrangle the dataset into an MVP shape

**Comment by gabsie** [comment]
We discussed with Enrique yesterday that he can try out with this study: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE169207

**Comment by gabsie** [comment]
the two datasets are wrangled by Anu and Enrique. To schedule a meeting for next week and then follow up with MSK on correct experimental design. @anu-shiva @ESapenaVentura
