### ISSUE TITLE
create a bucket for schema files

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#10]
From hca-ebi-wrangler-central created by [amnonkhen](https://github.com/amnonkhen): ebi-ait/hca-ebi-wrangler-central#1164  

null

**Comment by amnonkhen** [comment]
- [x] create bucket
- [ ] configure policy, CORS
- [x] copy files straight from metadata-schema repo 
- [x] create cloudfront distribution
- [ ] verify access through aws url
- [ ] connect to morphic.bio domain and verify access

**Comment by amnonkhen** [comment]
sdfsdf
