### ISSUE TITLE
Metadata schema for Original Cell line

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#13]
From hca-ebi-wrangler-central created by [ESapenaVentura](https://github.com/ESapenaVentura): ebi-ait/hca-ebi-wrangler-central#1144  

- [x] discuss the required cell line fields amongst Anu and Enrique
- [x] set up the schema
- [ ] get approval/review from other DRACC members
- [ ] get feedback from DPCs

**Comment by gabsie** [comment]
Schema for these is established as version 1
