### ISSUE TITLE
Metadata schema for Study

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#16]
From hca-ebi-wrangler-central created by [gabsie](https://github.com/gabsie): ebi-ait/hca-ebi-wrangler-central#1133  

- [x] discuss the required study fields
- [x] set up the schema
- [x] get approval/review from other DRACC members
- [x] introduce the Dataset relevant fields as well under a study: DUO code and assay type
- [ ] get feedback/comments etc on the fields from DPC members

**Comment by ESapenaVentura** [comment]
From @gabsie:
@gabsie has to finally review @ESapenaVentura doc on dataset and align with the discussion with Tony.

**Comment by anu-shiva** [comment]
To be reopened if needed
