### ISSUE TITLE
Organise meetings with DAVs to discuss analysis requirements in schema

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#27]
- [x] Schedule interviews with DAV and DPC representatives in November.
- [x] Script for questions
- [x] present resultsat DWG meeting in November if possible

[DAV proposal](https://drive.google.com/drive/folders/1zQdeua7hee0oJ3d7ibzvIlV41dnb8SAh)

**Comment by anu-shiva** [comment]
Looking into the  DAVs plans- computational requirements

**Comment by anu-shiva** [comment]
1st meeting planned on the 6th Nov. @anu-shiva to prepare agenda and email Zoom invite
