### ISSUE TITLE
ontologised item w/o ontology label

### ISSUE THREAD

**Issue by amnonkhen** [morphic-bio/data-ingestion-development#31]
Modify the current ingest-client for HCA to accommodate MorPhiC ontology items. MorPhiC ontology items are expected to have no ```ontology_label``` field as compared to HCA.
- Prepare test cases for:
   - [x] SchemaTemplate
   - [x] Descriptor (Simple, Complex)
   - [ ] SchemaParser
   - [ ] VanillaSpreadsheetBuilder 
   - [ ] Investigate integration tests
 
- [X] Make changes in the code and run locally
          - Ontology items can be either of array or string type and be simple or composite objects with nested properties (ongoing and might not be relevant).
- [ ] Create pull request
- [ ] Merge to master/dev and test (probably need another ticket for this)

**Comment by KociOrges** [comment]
Different approach must be considered if ontology items have nested properties and/or whether they need to be handled/presented in a different way when adding them to the template. Need to make sure what is the case for these items and how they should be handled.

**Comment by gabsie** [comment]
this ticket has already been addressed in nested property ticket.
