### ISSUE TITLE
automated updates of schema changes

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#4]
From hca-ebi-wrangler-central created by [amnonkhen](https://github.com/amnonkhen): ebi-ait/hca-ebi-wrangler-central#1171  

In HCA schema changes are propagated to AWS using a webhook and a lambda function.
Similar approach can be used here.
See [discussion document](https://docs.google.com/document/d/1CiAk8dsq8npIPbmbZfSAh1FI45F793uI/edit)

**Comment by gabsie** [comment]
hey @amnonkhen - can you update us on this?

**Comment by KociOrges** [comment]
Have created a branch to adapt the metadata-schema-publisher Lamda function to MorPhiC: https://github.com/ebi-ait/metadata-schema-publisher/tree/feature/mc-4_morphic_publisher. Have also deployed the Lamda application into AWS. Currently finalising the dev environment.

**Comment by gabsie** [comment]
To be reviewed by Amnon/Enrique

**Comment by KociOrges** [comment]
Received comments on the PR (https://github.com/ebi-ait/metadata-schema-publisher/pull/8) from Amnon. Working on addressing the comments.

**Comment by KociOrges** [comment]
Currently at the stage of deploying the application to AWS dev to test it. Performing some AWS environment cleanup.

**Comment by KociOrges** [comment]
Have performed AWS cleanup and deployed and tested the application changes to AWS dev. Next step is a new PR for review.

**Comment by gabsie** [comment]
@KociOrges Alex to check if this was all done or not, and then see if can be closed off soon.
