### ISSUE TITLE
deploy MorPhiC's prod env

### ISSUE THREAD

**Issue by amnonkhen** [morphic-bio/data-ingestion-development#44]
- replicate the dev environment in the prod aws account
- do it using automation, e.g. terraform scripts

**Comment by gabsie** [comment]
Once the issue for subdirectories is solved for dev, this can be done for prod

**Comment by KociOrges** [comment]
Have replicated the dev environment in the prod aws account, using terraform scripts. The morphic-specific scripts can be found in this branch: https://github.com/ebi-ait/metadata-schema-publisher/tree/feature/mc-4_morphic_publisher. The prod URL of metadata-schemas is now served with its own CloudFront distribution and is available under this domain: https://schema.morphic.bio/index.html
