### ISSUE TITLE
Terraform for Morphic setup

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#5]
From hca-ebi-wrangler-central created by [amnonkhen](https://github.com/amnonkhen): ebi-ait/hca-ebi-wrangler-central#1170  

This will help CI/CD processes in the future and the build of new infrastructure.

**Comment by ESapenaVentura** [comment]
@dipayan1985 said:
> I can prioritize this from September 4.

**Comment by amnonkhen** [comment]
zxc

**Comment by amnonkhen** [comment]
done in MorPhiC-bio/data-ingestion-development#44
