### ISSUE TITLE
expose schema bucket as HTTP server - DEV environment

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#6]
From hca-ebi-wrangler-central created by [amnonkhen](https://github.com/amnonkhen): ebi-ait/hca-ebi-wrangler-central#1169  

- [x] expose a an http service using cloudfront
- [x] decide on a domain name - can it be: `schema.morphic.bio`
- [x] expose s3 bucket using the domain name - this is another ticket

**Comment by gabsie** [comment]
URL linked to the S3 bucket of the morphic schemas is not accessible

**Comment by amnonkhen** [comment]
cloudfront distribution stopped being accessible from the web. I don't know why.
@KociOrges to find out why

**Comment by KociOrges** [comment]
Schema bucket as http service is back again and currently accessible from the CloudFront distribution: https://d1wew2wvfg0okw.cloudfront.net/schema. Following the relevant configuration for HCA, needed to edit the `Legacy access identities` of the distribution and set it to the existing origin access identity for the morphic s3 bucket.

**Comment by gabsie** [comment]
@kociorges @amnonkhen - this needs to be replicated for production, Alex can do it, Amnon can review?
