### ISSUE TITLE
populate s3 bucket with schema files

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#7]
From hca-ebi-wrangler-central created by [amnonkhen](https://github.com/amnonkhen): ebi-ait/hca-ebi-wrangler-central#1168  

- [x] manually copy schema files to s3 bucket according to structure of HCA bucket
- [x] copy index.html that exposes bucket contents

**Comment by gabsie** [comment]
@amnonkhen is this now done?
