### ISSUE TITLE
Develop Tool for Parsing Metadata Spreadsheets

### ISSUE THREAD

**Issue by KociOrges** [morphic-bio/data-ingestion-development#73]

**Comment by KociOrges** [comment]
Develop or adapt an application/library to parse and consume Excel metadata spreadsheet files describing MorPhiC experiments. Review the existing **ingest-client** used in HCA for potential use or inspiration.

Review Dipayan's document showing an attempt to link the _**MorPhic Cell line -> differentiated cell line -> library preparation biomaterial -> sequencing file**_

**Comment by gabsie** [comment]
Hey @KociOrges and @dipayan1985  - is this ticket still valid?
