### ISSUE TITLE
September internal release organisation

### ISSUE THREAD

**Issue by gabsie** [morphic-bio/data-ingestion-development#81]
release date: 30sep
@alex/@dipayan to organise release folder and syncing as below:

- [x] Create a folder September-2024/ in **morphic-bio-data-release/**

**Syncing folders** from  **morphic-bio-processing/** to **morphic-bio-data-release/**

- [x] morphic-bio-processing/morphic-jax/JAX_RNAseq5_ExE_CBO/filtered to morphic-bio-data-release/September-2024/JAX_RNAseq5_ExE_CBO/filtered
- [x] morphic-bio-processing/morphic-jax/JAX_RNAseq5_ExE_CBO/processed to morphic-bio-data-release/September-2024/JAX_RNAseq5_ExE_CBO/processed
- [x] morphic-bio-processing/morphic-jax/JAX_RNAseq6_Diverse/filtered to  morphic-bio-data-release/September-2024/JAX_RNAseq6_Diverse/filtered
- [x] morphic-bio-processing/morphic-jax/JAX_RNAseq6_Diverse/processed to  morphic-bio-data-release/September-2024/JAX_RNAseq6_Diverse/processed
- [x] morphic-bio-processing/morphic-jax/JAX_RNAseq7_Reversion/filtered to morphic-bio-data-release/September-2024/JAX_RNAseq7_Reversion/filtered
- [x] morphic-bio-processing/morphic-jax/JAX_RNAseq7_Reversion/processed to morphic-bio-data-release/September-2024/JAX_RNAseq7_Reversion/processed
- [x] morphic-bio-processing/morphic-ucsf/UCSF_Bulk_EB_Timecourse/filtered to morphic-bio-data-release/September-2024/UCSF_Bulk_EB_Timecourse/filtered
- [x] morphic-bio-processing/morphic-ucsf/UCSF_Bulk_EB_Timecourse/processed to morphic-bio-data-release/September-2024/UCSF_Bulk_EB_Timecourse/processed

- [x] Create folder called 'source/' in each of the following:
- morphic-bio-data-release/September-2024/JAX_RNAseq5_ExE_CBO
- morphic-bio-data-release/September-2024/JAX_RNAseq6_Diverse
- morphic-bio-data-release/September-2024/JAX_RNAseq7_Reversion
- morphic-bio-data-release/September-2024/UCSF_Bulk_EB_Timecourse

Syncing files from  **morphic-bio/** to **morphic-bio-data-release/**
- [x] morphic-bio/morphic-jax/JAX_RNAseq5_ExE_CBO/ to morphic-bio-data-release/September-2024/JAX_RNAseq5_ExE_CBO/source/
- [x] morphic-bio/morphic-jax/JAX_RNAseq6_Diverse/ to morphic-bio-data-release/September-2024/JAX_RNAseq6_Diverse/source/
- [x] morphic-bio/morphic-jax/JAX_RNAseq7_Reversion/ to morphic-bio-data-release/September-2024/JAX_RNAseq7_Reversion/source/
- [x] morphic-bio/morphic-ucsf/UCSF_Bulk_EB_Timecourse/ to morphic-bio-data-release/September-2024/UCSF_Bulk_EB_Timecourse/source/

@anu 

- [x] Upload metadata
- [x] Verify with Hong on any new data
- [x] Send email

**Comment by gabsie** [comment]
folder metadata to be created for all September datasets

**Comment by anu-shiva** [comment]
the following to be synced again, as Hong has now deposited complete set of files

- morphic-bio-processing/morphic-ucsf/UCSF_Bulk_EB_Timecourse/filtered to morphic-bio-data-release/September-2024/UCSF_Bulk_EB_Timecourse/filtered

- morphic-bio-processing/morphic-ucsf/UCSF_Bulk_EB_Timecourse/processed to morphic-bio-data-release/September-2024/UCSF_Bulk_EB_Timecourse/processed

**Comment by dipayan1985** [comment]
Done.
