### ISSUE TITLE
Deposit files from the firstJAX study as private in ENA

### ISSUE THREAD

**Issue by gabsie** [morphic-bio/data-ingestion-development#99]
As part of the Deposit in Archive Milestone for all MorPhiC public release datasets, we need to organise the first dataset deposition in ENA. 

- [x] Document how to deposit the files from S3 to ENA private area
- [x] Prepare the mapping between MorPhiC spreadsheet to ENA entities
- [x] get extra information from submitters on library information
- [x] ensure the files are without y-reads - Anu
- [x] move the files over to ENA private area
- [x] establish a way to name the Morphic studies (Gabby + Anu)
- [x] submit the metadata with the correct mappings
- [ ] Anu to check if everything is correct

**Comment by gabsie** [comment]
@dipayan1985 can you please add links to your brokering docs here? both for submission and for checking if there's anything relevant?

**Comment by dipayan1985** [comment]
Added readme on how to use the metadata brokering utility - https://github.com/ebi-ait/subs-repository-broker
@gabsie @anu-shiva 
@anu-shiva 
I will demo this to you tomorrow.

**Comment by dipayan1985** [comment]
- The brokering guide - https://docs.google.com/document/d/1oVMnjZfkQ4b_XrYQjtuzO0asERhuLSSa/edit

- The first dataset brokering results - https://docs.google.com/document/d/1TywdawL0CDXVzkVUt-QYosbM6Rmi5PHj/edit?dls=true&tab=t.0

**Comment by dipayan1985** [comment]
- Webin account + how to get a token - not required for the brokering tool as it uses Webin super user and decrypted credentials are used from within the tool.
- For other cases (e.g. retrieval of samples from BioSamples), please follow the below steps:

1. Open Webin Authentication Service swagger UI - https://www.ebi.ac.uk/ena/submit/webin/auth/swagger-ui/index.html#/AuthenticationAPI/getToken
2. In **Try it out** enter the password and the user name (Webin-68480) to get a Webin Authentication token.
